### ISSUE TITLE
just fmt works but displays timeout

### ISSUE THREAD

**Issue by sebdotv** [linux-china/jetbrains-just-plugin#36]
When running Reformat Code, `just fmt` is properly executed but its completion is not detected in the IDE and a timeout is displayed:
> just fmt does not respond after 30 seconds.

![image](https://github.com/user-attachments/assets/d16186cc-e4f6-4df6-b61e-a495744274b6)

Version: 0.6.5

**Comment by linux-china** [comment]
could you try a simple justfile for format?   or use `just --unstable --fmt -f justfile` to test.

**Comment by sebdotv** [comment]
Running fmt outside of the plugin works perfectly, so I think the issue must be somewhere in detecting the command completion.
If it helps, I'm on Linux.

```
time just --unstable --fmt -f justfile
Wrote justfile to `[...]/justfile`
just --unstable --fmt -f justfile  0.00s user 0.00s system 79% cpu 0.003 total
```

**Comment by sebdotv** [comment]
Can we please reopen @linux-china? This bug still happens with 0.6.7 (sorry if my previous comment was unclear)

**Comment by linux-china** [comment]
@sebdotv  could you post your OS info and JetBrains IDE version?

**Comment by sebdotv** [comment]
Arch Linux 6.11.5-arch1-1
RustRover 2024.2.4
Build #RR-242.23726.110, built on October 24, 2024
Runtime version: 21.0.4+13-b509.26 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit

**Comment by linux-china** [comment]
@sebdotv  it's a bug caused by long-running status check.  Fixed with version 0.6.8.

**Comment by linux-china** [comment]
@sebdotv  if any problem, pls reopen the issue.

**Comment by sebdotv** [comment]
Still happens with 0.6.8 unfortunately (I don't have the rights to reopen the issue).

By the way, I don't see a related commit; was it pushed to `master`?

**Comment by linux-china** [comment]
it's here https://github.com/linux-china/jetbrains-just-plugin/commit/3a29a8817bec792894e31dc78eccd11094b66ee7  I will check again.

**Comment by cebas** [comment]
It's happening to me now, with just 1.40.0 and phpstorm 2024.3.5
The formatting works fine, and 30 seconds later, same error message as OP.
Running in console "just --fmt --unstable" also works fine.

**Comment by sebdotv** [comment]
Just wanted to clarify that this still happens (RustRover 2025.2.4.1 with plugin version 0.6.26)

**Comment by unclepomedev** [comment]
I can confirm this reproduces frequently in my environment.

- macOS (Apple Silicon)
- JetBrains 2025.3 series (IntelliJ IDEA, RustRover, PyCharm)
- Just plugin: 0.6.36

**Comment by lyrst** [comment]
I am not sure if this is related, but when I open just-file in IntelliJ, then CPU usage jumps to a super high level. 
When I deactivate the plugin, then it seems fine again. 

Do you need more information?

**Comment by linux-china** [comment]
> I am not sure if this is related, but when I open just-file in IntelliJ, then CPU usage jumps to a super high level. When I deactivate the plugin, then it seems fine again.
> 
> Do you need more information?

When you open the Justfile, and IDE will parse the file with lots of regex operation,  and it's CPU intensive. After parsing, and all is ok.
